### PR TITLE
[Network Config Mgr] Add NodeInfo APIs

### PR DESCRIPTION
**Pull request by pkommoju**
* NCM has API to create, delete, update nodeinfo in NCM.
* Bulk API is not tested. 
* NCM needs to have a rest client for NMM to push NodeInfo into NCM and it will come in the next commit.

### CODE REVIEW

**Review by xieus — CHANGES_REQUESTED** [review]
CI failed. Maybe you need to commit sth to trigger another run.

**Comment by pkommoju** [comment]
I will fix it and push again.

**Comment by pkommoju** [comment]
I pushed, adding a comment in test script.

**Comment by pkommoju** [comment]
Build success

**Review by xieus — APPROVED** [review]
LGTM.

**Pull request merged**
