### PR TITLE
Add performance statistics for port manager

### PR DESCRIPTION
**Pull request by chenpiaoping**
This PR proposes the following changes:
- Introduce a new annotation to keep track of method elapse time
- Record Web/Service/Repo layers of port creation
- Record elapse time of downstream microservices 
- Identify a potential bottleneck in one of downstream microservices

### CODE REVIEW

**Comment by chenpiaoping** [comment]
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() startTime(ns):457259527009000, endTime(ns): 457259545375700, duration(ns):18366700
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() startTime(ns):457259526852000, endTime(ns): 457259545508500, duration(ns):18656500
com.futurewei.alcor.portmanager.controller.PortController.listPort() startTime(ns):457259525747900, endTime(ns): 457259545775400, duration(ns):20027500
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() startTime(ns):457259625442500, endTime(ns): 457259629131500, duration(ns):3689000
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() startTime(ns):457259625377100, endTime(ns): 457259629257400, duration(ns):3880300
com.futurewei.alcor.portmanager.controller.PortController.listPort() startTime(ns):457259625152300, endTime(ns): 457259629321000, duration(ns):4168700
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() startTime(ns):457295773814400, endTime(ns): 457295778918200, duration(ns):5103800
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() startTime(ns):457295773769200, endTime(ns): 457295779053100, duration(ns):5283900
com.futurewei.alcor.portmanager.controller.PortController.listPort() startTime(ns):457295773608400, endTime(ns): 457295779119700, duration(ns):5511300
com.futurewei.alcor.portmanager.repo.PortRepository.getPortNeighbors() startTime(ns):457316265525000, endTime(ns): 457316266594400, duration(ns):1069400
com.futurewei.alcor.web.restclient.SecurityGroupManagerRestClient.bindSecurityGroups() startTime(ns):457316265315100, endTime(ns): 457316285168200, duration(ns):19853100
com.futurewei.alcor.web.restclient.IpManagerRestClient.allocateIpAddress() startTime(ns):457316261362600, endTime(ns): 457316286951100, duration(ns):25588500
com.futurewei.alcor.web.restclient.VpcManagerRestClient.getVpc() startTime(ns):457316258216800, endTime(ns): 457316296573400, duration(ns):38356600
com.futurewei.alcor.web.restclient.SubnetManagerRestClient.getSubnet() startTime(ns):457316288017600, endTime(ns): 457316302423100, duration(ns):14405500
com.futurewei.alcor.web.restclient.RouteManagerRestClient.getRouteBySubnetId() startTime(ns):457316302694100, endTime(ns): 457316311974300, duration(ns):9280200
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() startTime(ns):457321519281500, endTime(ns): 457321522006300, duration(ns):2724800
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() startTime(ns):457321519238500, endTime(ns): 457321522101600, duration(ns):2863100
com.futurewei.alcor.portmanager.controller.PortController.listPort() startTime(ns):457321519068100, endTime(ns): 457321522145800, duration(ns):3077700
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() startTime(ns):457321588193200, endTime(ns): 457321592109900, duration(ns):3916700
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() startTime(ns):457321588151900, endTime(ns): 457321592231700, duration(ns):4079800
com.futurewei.alcor.portmanager.controller.PortController.listPort() startTime(ns):457321587999400, endTime(ns): 457321592283700, duration(ns):4284300
com.futurewei.alcor.web.restclient.MacManagerRestClient.allocateMacAddress() startTime(ns):457316264447400, endTime(ns): 457322063327800, duration(ns):5798880400
com.futurewei.alcor.portmanager.repo.PortRepository.createPortAndNeighbor() startTime(ns):457322064366100, endTime(ns): 457322082208300, duration(ns):17842200
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.createPort() startTime(ns):457316252214900, endTime(ns): 457322110091200, duration(ns):5857876300
com.futurewei.alcor.portmanager.controller.PortController.createPort() startTime(ns):457316251498800, endTime(ns): 457322110166900, duration(ns):5858668100
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() startTime(ns):457322786250600, endTime(ns): 457322789564000, duration(ns):3313400
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() startTime(ns):457322786203400, endTime(ns): 457322789679900, duration(ns):3476500
com.futurewei.alcor.portmanager.controller.PortController.listPort() startTime(ns):457322786041100, endTime(ns): 457322789730600, duration(ns):3689500

**Comment by chenpiaoping** [comment]
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() startTime(ns):457953279897100, endTime(ns): 457953305379500, duration(ms):25
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() startTime(ns):457953277454300, endTime(ns): 457953305546400, duration(ms):28
com.futurewei.alcor.portmanager.controller.PortController.listPort() startTime(ns):457953274133600, endTime(ns): 457953305808500, duration(ms):31
com.futurewei.alcor.portmanager.repo.PortRepository.getPortNeighbors() startTime(ns):457973829620000, endTime(ns): 457973836343200, duration(ms):6
com.futurewei.alcor.web.restclient.SecurityGroupManagerRestClient.bindSecurityGroups() startTime(ns):457973829429900, endTime(ns): 457973849754800, duration(ms):20
com.futurewei.alcor.web.restclient.IpManagerRestClient.allocateIpAddress() startTime(ns):457973825153600, endTime(ns): 457973852427800, duration(ms):27
com.futurewei.alcor.web.restclient.VpcManagerRestClient.getVpc() startTime(ns):457973822055100, endTime(ns): 457973861192100, duration(ms):39
com.futurewei.alcor.web.restclient.SubnetManagerRestClient.getSubnet() startTime(ns):457973853337000, endTime(ns): 457973867982200, duration(ms):14
com.futurewei.alcor.web.restclient.RouteManagerRestClient.getRouteBySubnetId() startTime(ns):457973868279900, endTime(ns): 457973878095800, duration(ms):9
com.futurewei.alcor.web.restclient.MacManagerRestClient.allocateMacAddress() startTime(ns):457973828449600, endTime(ns): 457979685409700, duration(ms):5856
com.futurewei.alcor.portmanager.repo.PortRepository.createPortAndNeighbor() startTime(ns):457979686415700, endTime(ns): 457979708392800, duration(ms):21
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.createPort() startTime(ns):457973816021000, endTime(ns): 457979738084600, duration(ms):5922
com.futurewei.alcor.portmanager.controller.PortController.createPort() startTime(ns):457973815333600, endTime(ns): 457979738171500, duration(ms):5922
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() startTime(ns):457980415590800, endTime(ns): 457980419737400, duration(ms):4
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() startTime(ns):457980415166900, endTime(ns): 457980419890900, duration(ms):4
com.futurewei.alcor.portmanager.controller.PortController.listPort() startTime(ns):457980414969000, endTime(ns): 457980419969100, duration(ms):5
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() startTime(ns):457991527235200, endTime(ns): 457991530151200, duration(ms):2
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() startTime(ns):457991527188400, endTime(ns): 457991530248000, duration(ms):3
com.futurewei.alcor.portmanager.controller.PortController.listPort() startTime(ns):457991527031400, endTime(ns): 457991530292900, duration(ms):3
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() startTime(ns):457991616067300, endTime(ns): 457991618951700, duration(ms):2
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() startTime(ns):457991616023900, endTime(ns): 457991619054100, duration(ms):3
com.futurewei.alcor.portmanager.controller.PortController.listPort() startTime(ns):457991615849300, endTime(ns): 457991619098100, duration(ms):3

**Comment by chenpiaoping** [comment]
Sort by duration：
com.futurewei.alcor.portmanager.controller.PortController.createPort() duration(ms):5922
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.createPort() duration(ms):5922
com.futurewei.alcor.web.restclient.MacManagerRestClient.allocateMacAddress() duration(ms):5856
com.futurewei.alcor.web.restclient.VpcManagerRestClient.getVpc() duration(ms):39
com.futurewei.alcor.portmanager.controller.PortController.listPort() duration(ms):31
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() duration(ms):28
com.futurewei.alcor.web.restclient.IpManagerRestClient.allocateIpAddress() duration(ms):27
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() duration(ms):25
com.futurewei.alcor.portmanager.repo.PortRepository.createPortAndNeighbor() duration(ms):21
com.futurewei.alcor.web.restclient.SecurityGroupManagerRestClient.bindSecurityGroups() duration(ms):20
com.futurewei.alcor.web.restclient.SubnetManagerRestClient.getSubnet() duration(ms):14
com.futurewei.alcor.web.restclient.RouteManagerRestClient.getRouteBySubnetId() duration(ms):9
com.futurewei.alcor.portmanager.repo.PortRepository.getPortNeighbors() duration(ms):6
com.futurewei.alcor.portmanager.controller.PortController.listPort() duration(ms):5
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() duration(ms):4
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() duration(ms):4
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() duration(ms):3
com.futurewei.alcor.portmanager.controller.PortController.listPort() duration(ms):3
com.futurewei.alcor.portmanager.service.implement.PortServiceImpl.listPort() duration(ms):3
com.futurewei.alcor.portmanager.controller.PortController.listPort() duration(ms):3
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() duration(ms):2
com.futurewei.alcor.portmanager.repo.PortRepository.findAllPortEntities() duration(ms):2

**Comment by xieus** [comment]
@chenpiaoping Pretty good catch. It seems that mac address allocation took most of the port creation time. 5856ms/5922ms ~= 99%?

**Comment by chenpiaoping** [comment]
> @chenpiaoping Pretty good catch. It seems that mac address allocation took most of the port creation time. 5856ms/5922ms ~= 99%?

yes

**Comment by xieus** [comment]
> > @chenpiaoping Pretty good catch. It seems that mac address allocation took most of the port creation time. 5856ms/5922ms ~= 99%?
> 
> yes

Cool. I am assuming that the metrics was collected in one single server. 

We know what to do next then :-) Can we do this please:
- Get similar metrics for bulk port creation
- Collect metrics when microservices runs within containers (if not currently)
- Do a major code refactor of Virtual Mac Manager (VMM) to cut its allocation time within 10 ms - This can be done a follow-up PR or current PR (all up to you).

**Comment by chenpiaoping** [comment]
> > > @chenpiaoping Pretty good catch. It seems that mac address allocation took most of the port creation time. 5856ms/5922ms ~= 99%?
> > 
> > 
> > yes
> 
> Cool. I am assuming that the metrics was collected in one single server.
> 
> We know what to do next then :-) Can we do this please:
> 
> * Get similar metrics for bulk port creation
> * Collect metrics when microservices runs within containers (if not currently)
> * Do a major code refactor of Virtual Mac Manager (VMM) to cut its allocation time within 10 ms - This can be done a follow-up PR or current PR (all up to you).

Got it, this PR just adds the code to count the method call time, I'll build an end-to-end environment and continue to analyze performance bottlenecks.

**Comment by xieus** [comment]
@chenpiaoping We are going to merge this PR to alcor/master as it includes useful metrics for E2E testing. Meanwhile, please try to get similar metrics for bulk port creation and for the new Mac Manager when ready.

**Comment by chenpiaoping** [comment]
> @chenpiaoping We are going to merge this PR to alcor/master as it includes useful metrics for E2E testing. Meanwhile, please try to get similar metrics for bulk port creation and for the new Mac Manager when ready.

Ok, will do that.

**Pull request merged**
