### PR TITLE
Change the atomicity mode of some caches to transactional to fix issue 682

### PR DESCRIPTION
**Pull request by pkommoju**
Change all caches in Port Manager to transactional atomicity. Mixing caches of different atomicity mode under a transaction does not work in Ignite. This was  causing a failure in concurrent deletion of ports.

Linked to Issue #682

### CODE REVIEW

**Comment by xieus** [comment]
How about this PR? @pkommoju We are seeing quite a few of conflicting files.

**Comment by pkommoju** [comment]
Yes, this is expected because changes in two branches are getting combined into one. Let me take a look at them and attach a patch/comments about what to keep what to remove.

**Comment by pkommoju** [comment]
Abandon this PR and branch. I didn't realize it quickly enough.

PR#685 already brought in all these changes.

**Comment by xieus** [comment]
Close this PR as it is duplicated with PR #685.

**Pull request closed without merging**
