### PR TITLE
Automatically generate Swagger documentation

### PR DESCRIPTION
**Pull request by skdong**
[document] Swagger Rest API adoc (#150)(#176)

* Add SwaggerConfig to activate Swagger documentation when mvn test
* Add SwaggerJsonTest unit test for call Swagger API generating Swagger adoc documentation
* Swagger adoc documentation generated under target/swagger directory

### CODE REVIEW

**Comment by xieus** [comment]
@skdong The PR description looks pretty comprehensive. We only need to run "mvn test" to create the swagger adoc which will be generated under target/swagger directory, is that correct? 

Also, do we still need the other PR https://github.com/futurewei-cloud/alcor/pull/177?

**Comment by skdong** [comment]
@xieus yes We only need to run "mvn test" to create swagger adoc

**Comment by skdong** [comment]
@xieus This PR generates a Swagger adoc. Swagger generates documents through Spring Controller. PR # 177 generates adoc for each unit test. There is no corresponding Spring Controller for apigateway type api. It needs to be generated for unit test

**Comment by xieus** [comment]
@skdong Thanks for the response. I just tried to run "mvn test" in the swagger-auto branch, I didn't find the target/swagger sub-directory showed up. Something I might have missed?

**Comment by skdong** [comment]
@xieus This is because I turned off the unit test, the operation of generating the document was completed in a unit test, and now the unit test still depends on the database.

**Comment by skdong** [comment]
@xieus I can open the unit test and submit it, but It need to have a connectable database.

**Comment by xieus** [comment]
The Ignite UT issue is kind of headache. We will have to live without Ignite UTs until the issue is fixed. @chenpiaoping could you please take a look? This is becoming a blocking issue for us.

**Comment by xieus** [comment]
@skdong You should be unblocked. UTs are enabled (see PR https://github.com/futurewei-cloud/alcor/pull/186)

**Comment by skdong** [comment]
@xieus Ok I will unblock it

**Comment by skdong** [comment]
@xieus I only activated Uts of route, subnet, vpc, these microservices are normal now. Mac and private IP UTs still have errors when executed

mac microservice tips com.futurewei.alcor.common.db.CacheFacotry confilicts with com.futurewei.alcor.common.service.CacheFacotry

Private ip microservice prompt Unable to connect to localhost: 6379

**Comment by xieus** [comment]
> @xieus I only activated Uts of route, subnet, vpc, these microservices are normal now. Mac and private IP UTs still have errors when executed
> 
> mac microservice tips com.futurewei.alcor.common.db.CacheFacotry confilicts with com.futurewei.alcor.common.service.CacheFacotry
> 
> Private ip microservice prompt Unable to connect to localhost: 6379

@skdong I think the current PR looks good, and the Mac Manager and IP Manager UTs error could be fixed by service owner. 

@kimeunju108 please look into the Mac Manager UTs, and @chenpiaoping please look into the IP manager UTs.

**Pull request merged**
