### PR TITLE
[Netw Config Manager] Support coexist of gRPC and REST APIs 

### PR DESCRIPTION
**Pull request by pkommoju**
*  Fix NMM to NCM gRPC problem so that NCM can operate on both gRPC and REST.
* Tested NMM to NCM REST API by registering one NCM through NMM.
* Tested NMM to NCM gRPC by creating a port through postman and verifying that NCM has recieved goal state.
* NOTE: the branch ncmgrpcrest and the pull request from it are buggy and and should be abandoned.

### CODE REVIEW

**Review by DavidLiu506 — APPROVED** [review]

**Review by cj-chung — COMMENTED** [review]
Does the swagger UI working now for NCM?

>>> It does.

**Review by cj-chung — APPROVED** [review]
LGTM

**Comment by xieus** [comment]
@pkommoju We have one conflict with master after #703 is merged.

**Comment by pkommoju** [comment]
I have resolved the conflict on github, not sure if this worked or not, though.

**Pull request merged**
