### PR TITLE
[Alcor Tools] Set up a Swagger UI

### PR DESCRIPTION
**Pull request by skdong**
__List of Change__
* Add swagger dependencies
* Move swagger config from test to src

__NOTE__
* Need to execute microservices and access the UI of each microservices via /swagger-ui.html

### CODE REVIEW

**Comment by skdong** [comment]
@xieus Dr. xie this branch is to Setup Swagger UI

**Comment by xieus** [comment]
Awesome! Does this support API gateway as it has the complete set of customer-facing APIs?

**Comment by skdong** [comment]
API-Gateway's Swagger documentation is not supported at this time. The Spring Swagger generated documentation depends on some Spring annotations such as: RestController RequestMapping

**Comment by xieus** [comment]
Got it. Let us merge this PR first and continue to check other options.

**Pull request merged**
