### PR TITLE
Feature/add sleuth zipkin

### PR DESCRIPTION
**Pull request by haboy52581**
This PR is to add sleuth zipkin conf to enable monitor/tracing for spring boot apps
a. zipkin change client side is already in the file changed.
b. to run the zipkin server simplest way is using docker: docker run -d -p 9411:9411 openzipkin/zipkin

### CODE REVIEW

**Comment by xieus** [comment]
@haboy52581  Most payload is for L3 DPM change tracked by another PR #418. 

Please only include the zipkin change here.

**Comment by haboy52581** [comment]
> @haboy52581 Most payload is for L3 DPM change tracked by another PR #418.
> 
> Please only include the zipkin change here.

zipkin change client side is already in the file changed. 
to run the zipkin server simplest way is using docker:
docker run -d -p 9411:9411 openzipkin/zipkin

**Comment by haboy52581** [comment]
> @haboy52581 Most payload is for L3 DPM change tracked by another PR #418.
> 
> Please only include the zipkin change here.

done in c829920

**Comment by xieus** [comment]
@haboy52581 We would need to enable VPC workflow. Therefore, as discussed in the sync-up meeting, VPC and Route Mgr are two of the essential managers to enable this workflow.

**Comment by xieus** [comment]
This PR is superseded by PR #516.

**Pull request closed without merging**
