### PR TITLE
[Router Mgr] Remove transaction for a single cache operation

### PR DESCRIPTION
**Pull request by yanmo96**
- Remove try and catch to support concurrent.

### CODE REVIEW

**Review by cj-chung — APPROVED** [review]
LGTM

**Comment by cj-chung** [comment]
@yanmo96 BTW, please add `delete routing rule` part in this PR too (second half part in issue#648).

```
            // delete subnet routing rule in route manager
            try {
                this.subnetService.deleteSubnetRoutingRuleInRM(projectId, subnetId);
            } catch (HttpClientErrorException.NotFound e) {
                logger.warn(e.getMessage());
            }
```

**Review by cj-chung — CHANGES_REQUESTED** [review]
add second half part of issue#648 in this PR too.

**Review by xieus — APPROVED** [review]
LGTM. Discussed with @yanmo96 and @cj-chung, we will address Issue #648 in a new PR.

**Comment by cj-chung** [comment]
agree to create another PR for issue#648

**Review by cj-chung — APPROVED** [review]

**Comment by pkommoju** [comment]
Removing TXN over single cache was a good idea but these caches are modified in various places one after another and those operations should be under TXN for data consistency.
Perhaps, in another iteration TXN would be added in appropraite places.

**Pull request merged**
